arch: arm64-graviton2
virt: lxd
os: linux
dist: focal
group: edge

language: python

python:
  - "3.9"
  - "3.8"
  - "3.7"

install: pip install tox-travis

before_script: ./scripts/run_dynamodb_local.sh

script: tox

deploy:
  provider: pypi
  username: jacobneiltaylor
  distributions: "sdist bdist_wheel"
  skip_existing: true
  edge: true
  on:
    branch: main
    python: "3.9"
