name: Build Package

on:
  workflow_call: {}

jobs:
  build:
    name: Build Byrne package
    runs-on: ubuntu-latest
    container: jacobneiltaylor/builder:22.04
    steps:
      - name: Retrieve source
        uses: actions/checkout@v4
      - name: Install Poetry
        run: just install-poetry
      - name: Build package
        run: just build
      - name: Export package as artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist/byrne*
