name: Main Branch Push Workflow

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  style:
    uses: ./.github/workflows/style.yaml
  unit:
    uses: ./.github/workflows/unit.yaml
  integration:
    uses: ./.github/workflows/integration.yaml
    secrets: inherit
    needs: ["unit"]
  build:
    uses: ./.github/workflows/build.yaml
    needs:
      - integration
      - style