name: PyPI Package Publishing

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  id-token: write
  contents: read

jobs:
  integration_and_build:
    name: Run tests and build package
    uses: ./.github/workflows/integration_and_build.yaml

  publish:
    name: Publish package to PyPI
    runs-on: ubuntu-latest
    container: jacobneiltaylor/builder:22.04
    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v3
        with:
          name: release-dists
          path: dist/
      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
